name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run
      run: go run main.go

    - name: commit
      run: |
        git config --local user.email "techoc@foxmail.com"
        git config --local user.name "techoc"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/bili
        git pull --rebase
        git commit --allow-empty -m "a commit a day keeps your girlfriend away"
        git push